name: Create Release with Built .NET Framework App
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.2.0
      
      - name: Restore NuGet packages
        run: nuget restore
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build .NET Framework app
        run: msbuild /p:Configuration=Release
        
      - name: Archive app
        run: |
          mkdir build
          cp BossDeathCounter/bin/Release/BossDeathCounter.exe build/BossDeathCounter.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Automatic release generated by GitHub Actions.
          draft: false
          prerelease: false

      - name: Upload App
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build\BossDeathCounter.exe
          asset_name: BossDeathCounter.exe
          asset_content_type: application/octet-stream
