name: Create Release with Built .NET Framework App
on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 4.8.2  # Change to the desired .NET Framework version

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build .NET Framework app
        run: dotnet build --configuration Release

      - name: Archive app
        run: |
          mkdir build
          cp -r BossDeathCounter/bin/Release/* build/
          zip -r app.zip build/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Automatic release generated by GitHub Actions.
          draft: false
          prerelease: false

      - name: Upload App
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app.zip
          asset_name: app.zip
          asset_content_type: application/zip
